import React from "react";

export const ProductData = () => {
   [
      {
          "_id": "5fd88bffd3559537a81d117d",
          "id": "2306",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket (Double)",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 380,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c9",
          "id": "4209",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Cotton)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 220,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d1",
          "id": "4217",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c0",
          "id": "4110",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fda587668a9a00c405a1e20",
          "id": "4552",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Havvy Huddi",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114a",
          "id": "1213",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Waist Coat / Coati",
          "category": "Women's wear",
          "service": "Wash And Iron",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1192",
          "id": "3109",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lather Jacket",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 500,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121c",
          "id": "6202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Presentation dress (Sari, Blouse, Petticoat)",
          "description": "Sari-2pis, Blouse-2pis, Petticoat-2pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 130,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f4",
          "id": "5210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f6",
          "id": "5212",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain / Fancy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 425,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1154",
          "id": "2102",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / jeans / Pajama)",
          "service": "Wash And Fold",
          "category": "Men's Wear",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ab",
          "id": "3218",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blazer / Coat / Jacket",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1170",
          "id": "2213",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11bb",
          "id": "4105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 500,
          "quantity": 1
      },
      {
          "_id": "62a7bd7a4f12cb50591df5da",
          "id": "2204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Cardigan)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 85,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1197",
          "id": "3114",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d117e",
          "id": "2307",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket Cover / Bed Cover",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1181",
          "id": "2310",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sofa Cover",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11de",
          "id": "5103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Topwear (Shirt / T-shirt / Fatua)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1168",
          "id": "2205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Home Wear (Nightdress / Normal Maxi)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d9",
          "id": "4308",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Towel",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11cc",
          "id": "4212",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Dupatta (Fancy)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ca",
          "id": "4210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Long Dress",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1147",
          "id": "1210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blazer / Coat / Jacket",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 140,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118b",
          "id": "3102",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Jeans / Pajama)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11fe",
          "id": "5220",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Cotton)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 380,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118f",
          "id": "3106",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Socks / Shorts / Under Shirt)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11fa",
          "id": "5216",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Silk)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 190,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f5",
          "id": "5211",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 145,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114b",
          "id": "1214",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Overcoat",
          "category": "Women's wear",
          "service": "Wash And Iron",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11eb",
          "id": "5201",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116a",
          "id": "2207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Blous / Petticoat / Under Garments)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119b",
          "id": "3202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear ( Trouser / Slack / Pazama)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11df",
          "id": "5104",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Jeans / Pajama)",
          "category": "Men's Wear",
          "service": "Emergency service",
          "subservice": "Wash And Iron",
          "price": 70,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1221",
          "id": "6207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Marriage Set ( Benarasi, Petticote, Blouse)",
          "description": "Benarasi-2pis, Petticode-2pis, Blouse-2pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1183",
          "id": "2312",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Cushion / Pillow",
          "category": "Household",
          "service": "Wash And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115f",
          "id": "2113",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 210,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1144",
          "id": "1207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Blous / Petticoat / Under Garments)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 35,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1175",
          "id": "2218",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blazer / Coat / Jacket",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ee",
          "id": "5204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear ( Trouser / Slack / Pazama)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 360,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e6",
          "id": "5111",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Premium (Blazer / Coat / Jacket)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 160,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a2",
          "id": "3209",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Scarf / Dupatta / Orna / Muffler)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114e",
          "id": "1303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Towel",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d113b",
          "id": "1111",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser + Waist Coat)",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 220,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1187",
          "id": "2316",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Car Seat Cover",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1146",
          "id": "1209",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 35,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119c",
          "id": "3203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Long Dress (Borka / Jumpsuit / Arabian Dress)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 20,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f2",
          "id": "5208",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lehenga (Plain / Heavy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 780,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c4",
          "id": "4204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt (Medium)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "61927191e928d2001743ff98",
          "id": "6731",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Under Shirt",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 20,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1189",
          "id": "2318",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Travel Bag",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 280,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11af",
          "id": "3302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Pillow Case",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d0",
          "id": "4216",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Coat",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1161",
          "id": "2115",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Overcoat / Overall",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1139",
          "id": "1109",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Panjabi",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1166",
          "id": "2203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Scarf / Dupatta / Orna / Muffler)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119f",
          "id": "3206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree - Exclusive (Benarasi / Jamdani / Katan)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d8",
          "id": "4307",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Carpet",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c2",
          "id": "4202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lehenga (Plain)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a8",
          "id": "3215",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez (3 Pcs)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11bc",
          "id": "4106",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lather Jacket",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 400,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e0",
          "id": "5105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Jeans / Pajama)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1155",
          "id": "2103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blazer / Coat / Jacket",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1199",
          "id": "3116",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Home Wear (Sleeping suit / Nightdress)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 15,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1174",
          "id": "2217",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116f",
          "id": "2212",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Waist Coat / Coati",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1193",
          "id": "3110",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120a",
          "id": "5303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Single)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1210",
          "id": "5309",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sofa Cover",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 170,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d113d",
          "id": "1113",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 70,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1151",
          "id": "1306",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Prayer Cap / Napkin etc)",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1162",
          "id": "2116",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1179",
          "id": "2302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Pillow Case",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1217",
          "id": "6102",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Presentation dress (Shirt, Pant, Tie)",
          "description": "Shirt-2pis, Pant-2pis, Tie-2pis",
          "category": "Men's Wear",
          "service": "Subscription",
          "price": 85,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114f",
          "id": "1304",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a1",
          "id": "3208",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Kameez",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1211",
          "id": "5310",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Carpet",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d7",
          "id": "4306",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sofa Cover",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ac",
          "id": "3219",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f8",
          "id": "5214",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain / Fancy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 490,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a4",
          "id": "3211",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Home Wear (Nightdress / Normal Maxi)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 12,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1171",
          "id": "2214",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 130,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1153",
          "id": "2101",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "service": "Wash And Fold",
          "category": "Men's Wear",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11dd",
          "id": "5102",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Topwear (Shirt / T-shirt / Fatua)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1145",
          "id": "1208",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain Cotton / Plain Silk / Cotton Design)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f9",
          "id": "5215",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Silk)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 340,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116c",
          "id": "2209",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree - Exclusive (Benarasi / Jamdani / Katan)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 200,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a9",
          "id": "3216",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt Suit (2 Pcs)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 65,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d117f",
          "id": "2308",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Table Cover",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1176",
          "id": "2219",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e5",
          "id": "5110",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Premium (Blazer / Coat / Jacket)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 260,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ba",
          "id": "4104",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Jacket / Coat",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 200,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1202",
          "id": "5224",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sweater",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 210,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1160",
          "id": "2114",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser + Waist Coat)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 280,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1188",
          "id": "2317",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Prayer Cap / Napkin)",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ce",
          "id": "4214",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Gown",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 470,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1185",
          "id": "2314",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Doll (Big)",
          "category": "Household",
          "service": "Wash And Fold",
          "price": 320,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118a",
          "id": "3101",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b4",
          "id": "3307",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket Cover/ Bed Cover",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1180",
          "id": "2309",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Curtain (Per ft Width)",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 18,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c3",
          "id": "4203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lehenga (Heavy)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1206",
          "id": "5228",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Coat",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 170,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1209",
          "id": "5302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Single)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 65,
          "quantity": 1
      },
      {
          "_id": "61f528b81f4545001767b23d",
          "id": "467",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Jaar",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1219",
          "id": "6104",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer, Trouser, Waist Coat)",
          "description": "Blazer-2pis, Trouser-3pis, Waist Coat-2pis",
          "category": "Men's Wear",
          "service": "Subscription",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1196",
          "id": "3113",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1213",
          "id": "5210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Travel Bag",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 310,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e8",
          "id": "5113",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11da",
          "id": "4309",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Pillow",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11fd",
          "id": "5219",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Cotton)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 170,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115e",
          "id": "2112",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c6",
          "id": "4206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 180,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114c",
          "id": "1301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1137",
          "id": "1107",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Jubba / Kabuli suit",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 55,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120b",
          "id": "5204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Double)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 230,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11fb",
          "id": "5217",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Silk)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 630,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1152",
          "id": "1307",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Travel Bag",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 200,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f1",
          "id": "5207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lehenga (Plain / Heavy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron and Fold",
          "price": 380,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1220",
          "id": "6206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Set (Benarasi, Jamdani, Blouse)",
          "description": "Benarasi-2pis, Jamdani-1pis, Petticote-2pis, Blouse-2pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 475,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ef",
          "id": "5205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear ( Trouser / Slack / Pazama)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 420,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11cf",
          "id": "4215",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sweater",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120c",
          "id": "5305",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Double)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 130,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1218",
          "id": "6103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater, Hoodie)",
          "description": "Sweater-2pis, Hoodie-1pis",
          "category": "Men's Wear",
          "service": "Subscription",
          "price": 90,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1198",
          "id": "3115",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Muffler / Scarf / Cap / Tie)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d114d",
          "id": "1302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Pillow Case",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119e",
          "id": "3205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain Cotton / Plain Silk / Cotton Design)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120d",
          "id": "5306",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Double)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1200",
          "id": "5222",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 270,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116b",
          "id": "2208",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain Cotton / Plain Silk / Cotton Design)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 125,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1149",
          "id": "1212",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Kameez",
          "category": "Women's wear",
          "service": "Wash And Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116d",
          "id": "2210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1222",
          "id": "6301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Set (Bed sheet, Bed cover, Bed runner)",
          "description": "Bed sheet-2pis, Bed cover-2pis, Bed runner-1pis",
          "category": "Household",
          "service": "Subscription",
          "price": 247,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1204",
          "id": "5226",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sweater",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 310,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121a",
          "id": "6105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Marriage Set (Sherwani, Pant, Pajama, Panjabi)",
          "description": "Sherwani-1pis, Pant-2pis, Pajama-2pis, Panjabi-2pis",
          "category": "Men's Wear",
          "service": "Subscription",
          "price": 600,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d6",
          "id": "4305",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Door Mat",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 90,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a6",
          "id": "3213",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118d",
          "id": "3104",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d117b",
          "id": "2304",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Quilt",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11cb",
          "id": "4211",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Dupatta",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ad",
          "id": "3219",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Overcoat",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b5",
          "id": "3308",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Curtain (Per ft Width)",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 7,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121d",
          "id": "6203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Long Dress (Borka, Jumpsuit, Arabian Dress)",
          "description": "Borka-3pis, Jumpsuit-2pis, Arabian Dress-1pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 220,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b2",
          "id": "3305",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket (Single)",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1203",
          "id": "5225",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sweater",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 90,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d113a",
          "id": "1110",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser)",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 180,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1205",
          "id": "5227",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Coat",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11aa",
          "id": "3217",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f7",
          "id": "5213",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain / Fancy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 230,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1136",
          "id": "1105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Premium (Blazer / Coat / Jacket)",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 140,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b0",
          "id": "3303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Towel",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120f",
          "id": "5308",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sofa Cover",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 70,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1165",
          "id": "2202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Slack / Pazama)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d117c",
          "id": "2305",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket (Single)",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11fc",
          "id": "5218",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Cotton)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 320,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1223",
          "id": "6302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket Set (Blanket, Blanket Cover)",
          "description": "Blanket-2pis, Blanket Cover-2pis",
          "category": "Household",
          "service": "Subscription",
          "price": 650,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1195",
          "id": "3112",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Overcoat / Overall",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11bd",
          "id": "4107",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kurta",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 90,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1134",
          "id": "1103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 5,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a7",
          "id": "3214",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez (2 Pcs)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 20,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121b",
          "id": "6201",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt, T-shirt, Fatua)",
          "description": "Shirt-2pis, T-shirt-2pis, Fatua-2pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 110,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1142",
          "id": "1205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Home Wear (Nightdress / Normal Maxi)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115b",
          "id": "2109",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Socks / Shorts / Under Garments)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115a",
          "id": "2108",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Waist Coat)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a3",
          "id": "3210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Cardigan)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 25,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f3",
          "id": "5209",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1138",
          "id": "1108",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Socks / Shorts / Under Garments)",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 25,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d117a",
          "id": "2303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Towel",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1186",
          "id": "2315",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Doll(Small)",
          "category": "Household",
          "service": "Wash And Fold",
          "price": 200,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1178",
          "id": "2301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a0",
          "id": "3207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kameez / Kaftan / Apron / Tops",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c1",
          "id": "4201",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Trouser / Pajama)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 25,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c8",
          "id": "4208",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Silk)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 240,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1182",
          "id": "2311",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Chair / Cushion Cover",
          "category": "Household ",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1173",
          "id": "2216",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt Suit",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 200,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c5",
          "id": "4205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Skirt (Long)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b1",
          "id": "3304",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Quilt",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d120e",
          "id": "5307",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sofa Cover",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1148",
          "id": "1211",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree - Exclusive (Benarasi / Jamdani / Katan)",
          "category": "Women's wear",
          "service": "Wash And Iron",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ae",
          "id": "3301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1158",
          "id": "2106",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Jubba / Kabuli suit",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1157",
          "id": "2105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Home Wear (Sleeping suit / Nightdress)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1140",
          "id": "1203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Scarf / Dupatta / Orna / Muffler)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1164",
          "id": "2201",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e9",
          "id": "5114",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118c",
          "id": "3103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blazer / Coat / Jacket",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115c",
          "id": "2110",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Panjabi",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1208",
          "id": "5301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Single)",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e7",
          "id": "5112",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Premium (Blazer / Coat / Jacket)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 320,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1190",
          "id": "3107",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Panjabi",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 15,
          "quantity": 1
      },
      {
          "_id": "617ecb28a30bcd0017f0512e",
          "id": "9247",
          "ac": "d-block",
          "dc": "d-none",
          "name": "kameez",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 35,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d115d",
          "id": "2111",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Punjabi",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 120,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1141",
          "id": "1204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Cardigan)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119d",
          "id": "3204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Inner Wear (Blous / Petticoat / Under Garments)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 12,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11bf",
          "id": "4109",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 500,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1172",
          "id": "2215",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Dress / Gown",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d2",
          "id": "4301",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket / Quilt / Comforter (Single)",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1169",
          "id": "2206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Long Dress(Borka / Jumpsuit / Arabian Dress)",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1207",
          "id": "5229",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Coat",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 370,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1156",
          "id": "2104",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 85,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b9",
          "id": "4103",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (3 Psc)",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 350,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ed",
          "id": "5203",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear ( Trouser / Slack / Pazama)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 560,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d116e",
          "id": "2211",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Kameez",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "619e31e89b10bb0017c25126",
          "id": "3178",
          "ac": "d-block",
          "dc": "d-none",
          "name": "shirt",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ec",
          "id": "5202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ea",
          "id": "5115",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 510,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1215",
          "id": "5210",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Travel Bag",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 370,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11f0",
          "id": "5206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Lehenga (Plain / Heavy)",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 680,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b6",
          "id": "3309",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Table Cover / Sofa Cover / Chair Cover",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 15,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e3",
          "id": "5108",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 85,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d113f",
          "id": "1202",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Slack / Pazama)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 45,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1212",
          "id": "5311",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Carpet",
          "category": "Household",
          "service": "Emergency Service",
          "subservice": "Iron And Fold",
          "price": 25,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11c7",
          "id": "4207",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Fancy)",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1184",
          "id": "2313",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Floor / Prayer Mat",
          "category": "Household",
          "service": "Wash And Fold",
          "price": 55,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d4",
          "id": "4303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Single)",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 80,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1150",
          "id": "1305",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket",
          "category": "Household",
          "service": "Wash And Iron",
          "price": 15,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121f",
          "id": "6205",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Saree (Plain Cotton, Plain Silk, Cotton Design)",
          "description": "Plain Cotton-2pis, Plain Silk-2pis, Cotton Design-2pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 400,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e4",
          "id": "5109",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 210,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d121e",
          "id": "6204",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter wear (Sweater, Cardigan)",
          "description": "Sweater-2pis, Cardigan-3pis",
          "category": "Women's Wear",
          "service": "Subscription",
          "price": 180,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11dc",
          "id": "5101",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Topwear (Shirt / T-shirt / Fatua)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11a5",
          "id": "3212",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Waist Coat/ Coati",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d119a",
          "id": "3201",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Fatua)",
          "category": "Women's Wear",
          "service": "Iron And Fold",
          "price": 10,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11db",
          "id": "4310",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Travel Bag",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 250,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1201",
          "id": "5223",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 780,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e2",
          "id": "5107",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Winter Wear (Sweater / Hoodies)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Wash And Iron",
          "price": 160,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1177",
          "id": "2220",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Overcoat",
          "category": "Women's wear",
          "service": "Wash And Fold",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1163",
          "id": "2117",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Shawl",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d3",
          "id": "4302",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket / Quilt / Comforter (Double)",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 400,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1143",
          "id": "1206",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Long Dress (Borka /Jumpsuit / Arabian Dress)",
          "category": "Women's Wear",
          "service": "Wash And Iron",
          "price": 60,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d113c",
          "id": "1112",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Sherwani",
          "category": "Men's Wear",
          "service": "Wash And Iron",
          "price": 300,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b7",
          "id": "4101",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt / T-shirt / Trouser / Pajama)",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d118e",
          "id": "3105",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Waist Coat",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 50,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11d5",
          "id": "4304",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bed Sheet(Double)",
          "category": "Household",
          "service": "Dry Cleaning",
          "price": 160,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11ff",
          "id": "5221",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's Wear",
          "service": "Emergency Service",
          "subservice": "Wash and Iron",
          "price": 650,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11cd",
          "id": "4213",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Leather Jacket",
          "category": "Women's Wear",
          "service": "Dry Cleaning",
          "price": 450,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1159",
          "id": "2107",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Accessories (Muffler / Scarf / Cap / Tie)",
          "category": "Men's Wear",
          "service": "Wash And Fold",
          "price": 40,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11b3",
          "id": "3306",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Blanket (Double)",
          "category": "Household",
          "service": "Iron And Fold",
          "price": 380,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11e1",
          "id": "5106",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Bottom Wear (Trouser / Jeans / Pajama)",
          "category": "Men's Wear",
          "service": "Emergency Service",
          "subservice": "Dry Cleaning",
          "price": 100,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1191",
          "id": "3108",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Exclusive Panjabi",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 30,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1224",
          "id": "6303",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Tools Cover (Table Cover, Sofa Cover)",
          "description": "Table Cover-2pis, Sofa Cover-4pis, Car Seat Cover-6pis",
          "category": "Household",
          "service": "Subscription",
          "price": 150,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1194",
          "id": "3111",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Suit (Blazer + Trouser + Waist Coat)",
          "category": "Men's Wear",
          "service": "Iron And Fold",
          "price": 160,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d1216",
          "id": "6101",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Top Wear (Shirt, T-shirt, Fatua)",
          "description": "Shirt-2pis, T-shirt-2pis, Fatua-2pis",
          "category": "Men's Wear",
          "service": "Subscription",
          "price": 110,
          "quantity": 1
      },
      {
          "_id": "5fd88bffd3559537a81d11be",
          "id": "4108",
          "ac": "d-block",
          "dc": "d-none",
          "name": "Kurta (Fancy)",
          "category": "Men's Wear",
          "service": "Dry Cleaning",
          "price": 150,
          "quantity": 1
      }
  ]
  return {
  };
};
